// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbCzfQTjbFKurI1hvHp1YhStuHpe0pDrg',
    appId: '1:191125930432:web:e6befd29b723a328d88825',
    messagingSenderId: '191125930432',
    projectId: 'pantry-tracker-flutter',
    authDomain: 'pantry-tracker-flutter.firebaseapp.com',
    storageBucket: 'pantry-tracker-flutter.appspot.com',
    measurementId: 'G-T2THPF47X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcF05UgecmOR3AqhSyA7RoUd8UFqQ8088',
    appId: '1:191125930432:android:beb508b8276affccd88825',
    messagingSenderId: '191125930432',
    projectId: 'pantry-tracker-flutter',
    storageBucket: 'pantry-tracker-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAa4RfsmVIKCZHBmGaoGqCJFOfkNIqoTo',
    appId: '1:191125930432:ios:f15b3c7dde36bd6ed88825',
    messagingSenderId: '191125930432',
    projectId: 'pantry-tracker-flutter',
    storageBucket: 'pantry-tracker-flutter.appspot.com',
    iosBundleId: 'com.sohailokzz.pantry',
  );
}
